set_property SRC_FILE_INFO {cfile:{D:/Materiale pentru facultate/Anul 4/Semestrul 1/P3/Block_Design/Block_Design.srcs/constrs_1/new/Constraints_Block_Design.xdc} rfile:../../../Block_Design.srcs/constrs_1/new/Constraints_Block_Design.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F14 [get_ports {sys_clock}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C18 [get_ports {reset_0}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {usb_uart_rxd}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R12 [get_ports {usb_uart_txd}]
