# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints_Block_Design.xdc

# Block Designs: bd/Block_Design/Block_Design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Design || ORIG_REF_NAME==Block_Design} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_clk_wiz_0_0/Block_Design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Design_clk_wiz_0_0 || ORIG_REF_NAME==Block_Design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_microblaze_0_0/Block_Design_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Design_microblaze_0_0 || ORIG_REF_NAME==Block_Design_microblaze_0_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_dlmb_v10_0/Block_Design_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Design_dlmb_v10_0 || ORIG_REF_NAME==Block_Design_dlmb_v10_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_ilmb_v10_0/Block_Design_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Design_ilmb_v10_0 || ORIG_REF_NAME==Block_Design_ilmb_v10_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_dlmb_bram_if_cntlr_0/Block_Design_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Block_Design_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_ilmb_bram_if_cntlr_0/Block_Design_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Block_Design_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_lmb_bram_0/Block_Design_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Design_lmb_bram_0 || ORIG_REF_NAME==Block_Design_lmb_bram_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_mdm_1_0/Block_Design_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Design_mdm_1_0 || ORIG_REF_NAME==Block_Design_mdm_1_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_rst_clk_wiz_0_100M_0/Block_Design_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Design_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==Block_Design_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_axi_uartlite_0_0/Block_Design_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Design_axi_uartlite_0_0 || ORIG_REF_NAME==Block_Design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_microblaze_0_axi_periph_0/Block_Design_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Block_Design_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_FPU_IP_Slave_0_0/Block_Design_FPU_IP_Slave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Design_FPU_IP_Slave_0_0 || ORIG_REF_NAME==Block_Design_FPU_IP_Slave_0_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_xbar_0/Block_Design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Design_xbar_0 || ORIG_REF_NAME==Block_Design_xbar_0} -quiet] -quiet

# XDC: d:/Materiale pentru facultate/Anul 4/Semestrul 1/P3/Block_Design/Block_Design.gen/sources_1/bd/Block_Design/Block_Design_ooc.xdc
