@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Aug 21 01:15:41 +0300 2023
REM SW Build 3900603 on Fri Jun 16 19:31:24 MDT 2023
REM
REM IP Build 3900379 on Sat Jun 17 05:28:05 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim FPU_tb_behav -key {Behavioral:sim_1:Functional:FPU_tb} -tclbatch FPU_tb.tcl -view D:/Materiale_pentru_facultate/Licenta/Anul_4/Semestrul_1/P3/FPU/FPU_tb_behav.wcfg -log simulate.log"
call xsim  FPU_tb_behav -key {Behavioral:sim_1:Functional:FPU_tb} -tclbatch FPU_tb.tcl -view D:/Materiale_pentru_facultate/Licenta/Anul_4/Semestrul_1/P3/FPU/FPU_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
